<h1>Algorithm Step Links</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Section links are awesome.
Editor: Example Editor
Date: 1970-01-01
</pre>

<div algorithm>
  <dfn>Sandwhich</dfn>

    1. Plate
    1. If you are hungry, then:
       1. Bread {#foundation}
       1. Perform these substeps in parallel:
          1. Cheese {#protein}
          1. Lettuce
       1. Bread
    1. Napkin
</div>

<div>
  ## Heading
  Don't forget about [[#foundation]] and [[#protein]].

  Insert text here: <a algorithm-step href="#foundation"></a>,
  but <a algorithm-step href="#foundation">keep this text, please.</a>
</div>
